trigger:
- main

pool:
  vmImage: windows-latest

variables:
  bulidConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(bulidConfiguration)
  displayName: dotnet build $(bulidConfiguration)